### PR TITLE
Lots of data validation fixes

### LINKED ISSUE #222: Validate should probably limit field sizes
As summary.  We should reject attempts to create really really long string values.  

Its unlikely that particularly long strings would be legitimate config - attempts to do so are more likely to be either bugs in automated config generation or done with malicious intent.

### PR DESCRIPTION
**Pull request by robbrockbank**
Fixes #222

This also provides more information to the user, and allows the validation tag to be used to return a useful message to the user (which before we could not)

### CODE REVIEW

File: lib/numorstring/port.go [hunk 1]
```diff
@@ -50,13 +51,16 @@ func PortFromString(s string) (Port, error) {
...
 
 	if pmin, err := strconv.ParseUint(parts[0], 10, 16); err != nil {
-		return Port{}, errors.New("invalid minimum port number in range")
+		msg := fmt.Sprintf("invalid minimum port number in range (%s)", s)
+		return Port{}, errors.New(msg)
 	} else if pmax, err := strconv.ParseUint(parts[1], 10, 16); err != nil {
-		return Port{}, errors.New("invalid maximum port number in range")
+		msg := fmt.Sprintf("invalid maximum port number in range (%s)", s)
+		return Port{}, errors.New(msg)
 	} else {
```
Comment (gunjan5) [inline lib/numorstring/port.go]: unnecessary `else`

File: lib/numorstring/port.go [hunk 2]
```diff
@@ -50,13 +51,16 @@ func PortFromString(s string) (Port, error) {
 
 	parts := strings.Split(s, ":")
 	if len(parts) != 2 {
-		return Port{}, errors.New("invalid port format")
+		msg := fmt.Sprintf("invalid port format (%s)", s)
+		return Port{}, errors.New(msg)
```
Comment (gunjan5) [inline lib/numorstring/port.go]: just curious why can't the error message be inlined? like `errors.New(fmt.Sprintf("invalid port format (%s)", s))`

File: lib/validator/validator.go [hunk 3]
```diff
@@ -30,14 +32,35 @@ import (
 var validate *validator.Validate
 
 var (
-	nameRegex          = regexp.MustCompile("^[a-zA-Z0-9_.-]+$")
+	nameRegex          = regexp.MustCompile("^[a-zA-Z0-9_.-]{1,128}$")
 	interfaceRegex     = regexp.MustCompile("^[a-zA-Z0-9_-]{1,15}$")
-	labelRegex         = regexp.MustCompile("^[a-zA-Z_./-][a-zA-Z0-9_./-]*$")
+	labelRegex         = regexp.MustCompile("^[a-zA-Z_./-][a-zA-Z0-9_./-]{0,127}$")
```
Comment (gunjan5) [inline lib/validator/validator.go]: why is this `{0,127}` starting from `0` compared to `nameRegex`? does that mean we allow empty labels?

File: lib/validator/validator.go [hunk 4]
```diff
@@ -66,6 +89,23 @@ func init() {
...
+func reason(r string) string {
+	return reasonString + r
+}
+
+// extractReason extracts the error reason from the field tag in a validator
+// field error.
+func extractReason(tag string) string {
+	if strings.HasPrefix(tag, reasonString) {
+		return strings.TrimPrefix(tag, reasonString)
+	} else {
```
Comment (gunjan5) [inline lib/validator/validator.go]: unnecessary else

File: lib/validator/validator.go [hunk 5]
```diff
@@ -66,6 +89,23 @@ func init() {
...
+		return ""
```
Comment (gunjan5) [inline lib/validator/validator.go]: would there ever be a case where `reasonString` is not prefixed? if not we should be returning an error since returning an empty string is a silent failure

File: lib/validator/validator.go [hunk 6]
```diff
@@ -162,10 +188,12 @@ func validateProtocol(v *validator.Validate, structLevel *validator.StructLevel)
 	// names.
 	if num, err := p.NumValue(); err == nil {
 		if num == 0 {
-			structLevel.ReportError(reflect.ValueOf(p.NumVal), "Protocol", "protocol", "protocol number invalid")
+			structLevel.ReportError(reflect.ValueOf(p.NumVal),
+				"Protocol", "", reason("protocol number invalid"))
```
Comment (gunjan5) [inline lib/validator/validator.go]: for my understanding, why did you change `"protocol"` field to `""` in this one and all the following `ReportError`?

File: lib/numorstring/port.go (hunk 2 above)
Comment (robbrockbank) [inline lib/numorstring/port.go]: it can - i think having it on a separate line is easier to read tho.

I'll change it if its bugging you or if it is against golang suggested practices.  Let me know.

File: lib/validator/validator.go (hunk 3 above)
Comment (robbrockbank) [inline lib/validator/validator.go]: Nope the label regex has an initial char [a-zA-Z_./-] followed by 0-127 [a-zA-Z0-9_./-]

Basically, the first char cannot be a number - the 0,127 applies to the second character

File: lib/validator/validator.go (hunk 5 above)
Comment (robbrockbank) [inline lib/validator/validator.go]: Well that depends on the validator that someone has written - I agree that it should always be set, but better to  have it error something sensible rather than panic or similar.   This won't cause a silent failure - it just returns less information to the user.

File: lib/errors/errors.go [hunk 7]
```diff
@@ -65,23 +65,33 @@ type ErrorValidation struct {
...
 	if len(e.ErroredFields) == 0 {
 		return "unknown validation error"
 	} else if len(e.ErroredFields) == 1 {
-		return fmt.Sprintf("error with field %s = '%v'",
-			e.ErroredFields[0].Name,
-			e.ErroredFields[0].Value)
+		f := e.ErroredFields[0]
+		if f.Reason == "" {
+			return fmt.Sprintf("error with field %s = '%v'",
+				f.Name, f.Value)
```
Comment (robbrockbank) [inline lib/errors/errors.go]: Good question,  it is possible that the Value could be nil I guess (if someone specified null in the json)

But Sprintf handles it gracefully (it writes out `<nil>`)

File: lib/numorstring/port.go (hunk 2 above)
Comment (gunjan5) [inline lib/numorstring/port.go]: its not bugging me, I was just curious. Don't think there's a golang best practice for this, I was just wondering about the extra variable creation in memory
