### PR TITLE
Get tests running with k8s 1.10

### LINKED ISSUE #891: Tests fail with K8s 1.10.4
Hit in PR #890 
More diags at https://semaphoreci.com/calico/libcalico-go/branches/pull-request-890/builds/3
```
Failure [1.032 seconds]

Test Syncer API for Kubernetes backend [It] should patch Pod (with existing annotations) with our PodIP annotation 

/go/src/github.com/projectcalico/libcalico-go/lib/backend/k8s/k8s_test.go:1409



  Expected error:

      <*errors.StatusError | 0xc42106e2d0>: {

          ErrStatus: {

              TypeMeta: {Kind: "", APIVersion: ""},

              ListMeta: {SelfLink: "", ResourceVersion: "", Continue: ""},

              Status: "Failure",

              Message: "object is being deleted: pods \"test-syncer-basic-pod\" already exists",

              Reason: "AlreadyExists",

              Details: {

                  Name: "test-syncer-basic-pod",

                  Group: "",

                  Kind: "pods",

                  UID: "",

                  Causes: nil,

                  RetryAfterSeconds: 0,

              },

              Code: 409,

          },

      }

      object is being deleted: pods "test-syncer-basic-pod" already exists

  not to have occurred



  /go/src/github.com/projectcalico/libcalico-go/lib/backend/k8s/k8s_test.go:1317

------------------------------

••••••



Summarizing 3 Failures:



[Fail] Test Syncer API for Kubernetes backend [It] should handle a basic Pod 

/go/src/github.com/projectcalico/libcalico-go/lib/backend/k8s/k8s_test.go:234



[Fail] Test Syncer API for Kubernetes backend [It] should patch Pod (with no existing annotations) with our PodIP annotation 

/go/src/github.com/projectcalico/libcalico-go/lib/backend/k8s/k8s_test.go:1317



[Fail] Test Syncer API for Kubernetes backend [It] should patch Pod (with existing annotations) with our PodIP annotation 

/go/src/github.com/projectcalico/libcalico-go/lib/backend/k8s/k8s_test.go:1317



Ran 16 of 16 Specs in 105.474 seconds

FAIL! -- 13 Passed | 3 Failed | 0 Pending | 0 Skipped --- FAIL: TestModel (105.48s)
```

### PR DESCRIPTION
**Pull request by neiljerram**
Fixes #891

### CODE REVIEW

File: lib/backend/k8s/k8s_test.go [hunk 1]
```diff
@@ -1284,7 +1284,12 @@ var _ = Describe("Test Syncer API for Kubernetes backend", func() {
 		})
 
 		By("Deleting the Pod and expecting the wep to be deleted", func() {
-			err = c.ClientSet.CoreV1().Pods("default").Delete(pod.ObjectMeta.Name, &metav1.DeleteOptions{})
+			var zero int64
+			policy := metav1.DeletePropagationBackground
```
Comment (caseydavenport) [inline lib/backend/k8s/k8s_test.go]: Interesting - what are the dependents that we need to propagate deletion to now?

Comment (neiljerram) [reply lib/backend/k8s/k8s_test.go]: I'm afraid I don't know in detail; but I could observe in the logs that libcalico-go was never seeing a Deleted event for the Pod, and then it was a bit of trial and error and luck that discovered this 'solution'.

That said, I guess it could be the volume that is automatically set up to hold the default service account?  As in the kube-controller PR that was one of the things that showed up as different between `pod` and `podNow`.

Would you like me to dig more on this before we finalize these PRs?  Or are you happy for us to run with this and keep our ears open for more detail in k8s work overall?

Comment (caseydavenport) [reply lib/backend/k8s/k8s_test.go]: Nah, I'm happy to merge as is. I was just curious.

Comment (neiljerram) [reply lib/backend/k8s/k8s_test.go]: OK, thanks.  (Also I meant to say "the volume that is automatically set up to hold the default service account *secret*", above.)
