### PR TITLE
Handle missing node better

### LINKED ISSUE #345: Missing node information for WorkloadEndpoint using KDD
Seen in Felix logs using the Kubernetes datastore driver.  Looks like there are some cases where we send through updates without a Node field populated.

```
10232 2017-02-16 20:59:04.579 [WARNING][32] stats_collector.go 110: Failed to get hostname key=WorkloadEndpoint(node=, orchestrator=k8s, workload=cali-ns-0.client0-cali-ns-0-765639624-00z3d, name=eth0)
10233 2017-02-16 20:59:04.579 [WARNING][32] stats_collector.go 110: Failed to get hostname key=WorkloadEndpoint(node=, orchestrator=k8s, workload=cali-ns-0.client0-cali-ns-0-765639624-01n3c, name=eth0)
10234 2017-02-16 20:59:04.581 [WARNING][32] stats_collector.go 110: Failed to get hostname key=WorkloadEndpoint(node=, orchestrator=k8s, workload=cali-ns-0.client0-cali-ns-0-765639624-05m2v, name=eth0)
10235 2017-02-16 20:59:04.582 [WARNING][32] stats_collector.go 110: Failed to get hostname key=WorkloadEndpoint(node=, orchestrator=k8s, workload=cali-ns-0.client0-cali-ns-0-765639624-06nkt, name=eth0)
```

Note that when this happened, we saw that one of the Kubernetes nodes had gone into a failed state (can't remember which state exactly), which might be related.

CC @frnkdny

### PR DESCRIPTION
**Pull request by caseydavenport**
Fix #345 

We receive Pods with a missing NodeName when they are first created in the k8s API, but not yet scheduled.

This PR makes the syncer ignore any such updates, and updates the code to be consistent in using `isCalicoPod` for determining if a Pod should be shown through the Calico API as a workloadEndpoint.

### CODE REVIEW

File: lib/backend/k8s/conversion.go [hunk 1]
```diff
@@ -209,21 +223,21 @@ func (c converter) podToWorkloadEndpoint(pod *kapiv1.Pod) (*model.KVPair, error)
...
 	// If the pod doesn't have an IP address yet, then it hasn't gone through CNI.
-	ipNets := []cnet.IPNet{}
-	if c.hasIPAddress(pod) {
-		// Parse the Pod's IP address.
-		_, ipNet, err := cnet.ParseCIDR(fmt.Sprintf("%s/32", pod.Status.PodIP))
-		if err != nil {
-			return nil, err
-		}
-		ipNets = []cnet.IPNet{*ipNet}
+	if !c.hasIPAddress(pod) {
```
Comment (robbrockbank) [inline lib/backend/k8s/conversion.go]: Should we just be calling our to isCalicoPod() here?

Also, it feels like this will cause errors to trickle up in the list processing and syncer?  Is that not the case?    e.g. in the syncer there is a call to pofdToWorkloadEndpoint() that ignores the errors - is there a chance it will get called for non calico pods and thus error resulting in a panic?

Comment (robbrockbank) [inline lib/backend/k8s/conversion.go]: It feels like the requirement to check if it is a Calico pod is split between the podToWorkloadEndpoint() code and also by some of the code that calls in to podToWorkloadEndpoint() - I just wonder if the interface should be defined that podToWorkloadEndpoint() should not be called for non-Calico pods (and maybe panic if it is).... dunno just thinking out loud.

Comment (caseydavenport) [inline lib/backend/k8s/conversion.go]: Yeah - I agree.

I think we can safely make the contract "Only call podToWorkloadEndpoint on something that passes isCalicoPod, and expect a panic otherwise."

Comment (caseydavenport) [inline lib/backend/k8s/conversion.go]: Actually, I don't want the result to be a panic.

Comment (robbrockbank) [inline lib/backend/k8s/conversion.go]: Yeah I wasn't sure either.....  probably a better for podToWorkloadEndpoint to return a specific error or summint and handle that error - but then is it worth it?

Comment (caseydavenport) [inline lib/backend/k8s/conversion.go]: OK - I've updated so that the error is returned if not a calico pod, and all instances handle the error (and/or check isCalicoPod beforehand).

File: lib/backend/k8s/syncer.go [hunk 2]
```diff
@@ -424,18 +424,20 @@ func (syn *kubeSyncer) performSnapshot() ([]model.KVPair, map[string]bool, resou
...
 				continue
 			}
 
 			// Convert to a workload endpoint.
-			wep, _ := syn.kc.converter.podToWorkloadEndpoint(&po)
-			if wep != nil {
-				snap = append(snap, *wep)
-				keys[wep.Key.String()] = true
+			wep, err := syn.kc.converter.podToWorkloadEndpoint(&po)
+			if err == nil {
```
Comment (robbrockbank) [inline lib/backend/k8s/syncer.go]: !=

Comment (robbrockbank) [inline lib/backend/k8s/syncer.go]: are we missing a test here that we didn't spot that?

Comment (caseydavenport) [inline lib/backend/k8s/syncer.go]: d'oh, yes.  I'll fix.

Comment (caseydavenport) [inline lib/backend/k8s/syncer.go]: @robbrockbank I've added some FV infrastructure to this PR which validates that updates actually do show up in the syncer.

It doesn't go all the way, in that:
- I haven't added it to all of the different resources tests yet.
- It doesn't check the content yet, just that an update was received.

It catches the above `==` vs `!=` bug.  I think this is good enough for now, but we should fix those two bullets in the near future to make these tests more robust.

File: lib/backend/k8s/k8s_fv_test.go [hunk 3]
```diff
@@ -71,10 +77,48 @@ func (c cb) OnUpdates(updates []api.Update) {
...
+}
+
+func (c cb) ProcessUpdates() {
+	for u := range c.updateChan {
+		// Store off the update so it can be checked by the test.
+		// Use a mutex for safe cross-goroutine reads/writes.
+		c.Lock.Lock()
+		if u.UpdateType == api.UpdateTypeKVUnknown {
+			// We should never get this!
+			log.Panic("Recieved Unkown update type")
```
Comment (robbrockbank) [inline lib/backend/k8s/k8s_fv_test.go]: Unkown

Comment (robbrockbank) [inline lib/backend/k8s/k8s_fv_test.go]: Recieved

**Comment by caseydavenport** [comment]
@tomdee @robbrockbank what are your thoughts on this for v2.1? 

It's not tiny, but without it we produce some ERROR logs during mainline operation which are benign.

I could make a much smaller stopgap PR which just downgrades the log level for v2.1.0 and merge this after?

**Comment by robbrockbank** [comment]
LGTM (by the way).

A large chunk of this PR is testing, and the remainder adds improved testing of the pod and adds more logging.  If you think the logging improvements will themselves be beneficial for debugging any potential issues then I'm personally ok with this going in to v2.1.  - I don't personally have a feel for that though.
