### PR TITLE
Return ErrorResourceDoesNotExist when pod is not ready to be displayed

### LINKED ISSUE #415: Panic while trying to delete a pod with KDD backend
```
kubectl delete -f nginx.yaml
```

logs:
```
May 08 23:03:21 node-01 kubelet[15267]: time="2017-05-08T23:03:21Z" level=info msg="Configured environment: [LANG=en_US LANGUAGE=en_US: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin KUBELET_KUBECONFIG_ARGS=--kubeconfig=/etc/kubernetes/kubelet.conf --require-kubeconfig=true KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin KUBELET_DNS_ARGS=--cluster-dns=10.96.0.10 --cluster-domain=cluster.local KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt CNI_COMMAND=DEL CNI_CONTAINERID=cf6b2529fe92e81741f83a85b3855f44cc6810eb060fcb10a8aafc55c563252f CNI_NETNS= CNI_ARGS=IgnoreUnknown=1;IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=my-nginx-3047691970-t46th;K8S_POD_INFRA_CONTAINER_ID=cf6b2529fe92e81741f83a85b3855f44cc6810eb060fcb10a8aafc55c563252f CNI_IFNAME=eth0 CNI_PATH=/opt/cni/bin:/opt/calico/bin DATASTORE_TYPE=kubernetes KUBECONFIG=/etc/cni/net.d/calico-kubeconfig K8S_API_ENDPOINT=https://10.96.0.1:443 K8S_API_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJjYWxpY28tbm9kZS10b2tlbi1xN3MwYiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJjYWxpY28tbm9kZSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjUxYjkxMzE3LTM0MzgtMTFlNy05ZjdmLTA4MDAyN2VlMzI5OCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTpjYWxpY28tbm9kZSJ9.TeQY6W5-CCSs7e-5dLR0iqqnnVmus68c_WM-4D_8soipeVPDoAaukqNOEMuzUBgu6z6j9kbwOoZwPGQk0o4Wcdu-_YeKeDiLq6K9XQJf6Qabr8lmbLYEePUF5nW4Yux77bkNEZN-1HDxyBn1y18zga19iKdTO2S69RA3WlvGn2-3ESYFHJlq2UXxwcr-BKcELyw3t4v1RnZpmUSYAeK7w4dcZdV9GUoTfX4wUVXyU1kw3dcmANWAwajxTz4TuSJBiwOnThZiPjOriiIFAgvHM-bRIBUNOBUc3NDPWcxe0WBnWQXUhOW_GJ9KZgIW_IrOMUwyATQhy6ViWnSWtN8ipA]"
May 08 23:03:21 node-01 kubelet[15267]: time="2017-05-08T23:03:21Z" level=info msg="Loading config from environment"
May 08 23:03:21 node-01 kubelet[15267]: time="2017-05-08T23:03:21Z" level=debug msg="Using datastore type 'kubernetes'"
May 08 23:03:21 node-01 kubelet[15267]: time="2017-05-08T23:03:21Z" level=debug msg="Building client for config: &{Kubeconfig:/etc/cni/net.d/calico-kubeconfig K8sAPIEndpoint:https://10.96.0.1:443 K8sKeyFile: K8sCertFile: K8sCAFile: K8sAPIToken:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJjYWxpY28tbm9kZS10b2tlbi1xN3MwYiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJjYWxpY28tbm9kZSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjUxYjkxMzE3LTM0MzgtMTFlNy05ZjdmLTA4MDAyN2VlMzI5OCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTpjYWxpY28tbm9kZSJ9.TeQY6W5-CCSs7e-5dLR0iqqnnVmus68c_WM-4D_8soipeVPDoAaukqNOEMuzUBgu6z6j9kbwOoZwPGQk0o4Wcdu-_YeKeDiLq6K9XQJf6Qabr8lmbLYEePUF5nW4Yux77bkNEZN-1HDxyBn1y18zga19iKdTO2S69RA3WlvGn2-3ESYFHJlq2UXxwcr-BKcELyw3t4v1RnZpmUSYAeK7w4dcZdV9GUoTfX4wUVXyU1kw3dcmANWAwajxTz4TuSJBiwOnThZiPjOriiIFAgvHM-bRIBUNOBUc3NDPWcxe0WBnWQXUhOW_GJ9KZgIW_IrOMUwyATQhy6ViWnSWtN8ipA}"
May 08 23:03:21 node-01 kubelet[15267]: time="2017-05-08T23:03:21Z" level=debug msg="Config overrides: &{AuthInfo:{LocationOfOrigin: ClientCertificate: ClientCertificateData:[] ClientKey: ClientKeyData:[] Token:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJjYWxpY28tbm9kZS10b2tlbi1xN3MwYiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJjYWxpY28tbm9kZSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjUxYjkxMzE3LTM0MzgtMTFlNy05ZjdmLTA4MDAyN2VlMzI5OCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTpjYWxpY28tbm9kZSJ9.TeQY6W5-CCSs7e-5dLR0iqqnnVmus68c_WM-4D_8soipeVPDoAaukqNOEMuzUBgu6z6j9kbwOoZwPGQk0o4Wcdu-_YeKeDiLq6K9XQJf6Qabr8lmbLYEePUF5nW4Yux77bkNEZN-1HDxyBn1y18zga19iKdTO2S69RA3WlvGn2-3ESYFHJlq2UXxwcr-BKcELyw3t4v1RnZpmUSYAeK7w4dcZdV9GUoTfX4wUVXyU1kw3dcmANWAwajxTz4TuSJBiwOnThZiPjOriiIFAgvHM-bRIBUNOBUc3NDPWcxe0WBnWQXUhOW_GJ9KZgIW_IrOMUwyATQhy6ViWnSWtN8ipA TokenFile: Impersonate: Username: Password: AuthProvider:<nil> Extensions:map[]} ClusterDefaults:{LocationOfOrigin: Server: APIVersion: InsecureSkipTLSVerify:false CertificateAuthority: CertificateAuthorityData:[] Extensions:map[]} ClusterInfo:{LocationOfOrigin: Server:https://10.96.0.1:443 APIVersion: InsecureSkipTLSVerify:false CertificateAuthority: CertificateAuthorityData:[] Extensions:map[]} Context:{LocationOfOrigin: Cluster: AuthInfo: Namespace: Extensions:map[]} CurrentContext: Timeout:}"
May 08 23:03:21 node-01 kubelet[15267]: time="2017-05-08T23:03:21Z" level=debug msg="Created k8s clientSet: &{DiscoveryClient:0xc4201f25c0 CoreV1Client:0xc420135680 AppsV1beta1Client:0xc4201357e0 AuthenticationV1beta1Client:0xc420135990 AuthorizationV1beta1Client:0xc420135af0 AutoscalingV1Client:0xc420135cb0 BatchV1Client:0xc420135e30 BatchV2alpha1Client:0xc420135f40 CertificatesV1alpha1Client:0xc4203220b0 ExtensionsV1beta1Client:0xc420322200 PolicyV1beta1Client:0xc420322300 RbacV1alpha1Client:0xc420322410 StorageV1beta1Client:0xc420322580}"
May 08 23:03:21 node-01 kubelet[15267]: time="2017-05-08T23:03:21Z" level=debug msg="Validate namespacedname: eth0"
May 08 23:03:21 node-01 kubelet[15267]: time="2017-05-08T23:03:21Z" level=debug msg="Validate namespacedname: default.my-nginx-3047691970-t46th"
May 08 23:03:21 node-01 kubelet[15267]: time="2017-05-08T23:03:21Z" level=debug msg="Validate namespacedname: k8s"
May 08 23:03:21 node-01 kubelet[15267]: time="2017-05-08T23:03:21Z" level=debug msg="Validate name: node-01"
May 08 23:03:21 node-01 kubelet[15267]: time="2017-05-08T23:03:21Z" level=debug msg="Performing 'Get' for WorkloadEndpoint(node=node-01, orchestrator=k8s, workload=default.my-nginx-3047691970-t46th, name=eth0)"
May 08 23:03:21 node-01 kubelet[15267]: time="2017-05-08T23:03:21Z" level=debug msg="Pod does not have an IP address." pod=my-nginx-3047691970-t46th
May 08 23:03:21 node-01 kubelet[15267]: panic: runtime error: invalid memory address or nil pointer dereference
May 08 23:03:21 node-01 kubelet[15267]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x134512a]
May 08 23:03:21 node-01 kubelet[15267]: goroutine 1 [running, locked to thread]:
May 08 23:03:21 node-01 kubelet[15267]: github.com/projectcalico/cni-plugin/vendor/github.com/projectcalico/libcalico-go/lib/client.(*workloadEndpoints).convertKVPairToAPI(0xc4201162a0, 0x0, 0xc4201401c0, 0x0, 0x0, 0x0)
May 08 23:03:21 node-01 kubelet[15267]:         /go/src/github.com/projectcalico/cni-plugin/vendor/github.com/projectcalico/libcalico-go/lib/client/workloadendpoint.go:180 +0x3a
May 08 23:03:21 node-01 kubelet[15267]: github.com/projectcalico/cni-plugin/vendor/github.com/projectcalico/libcalico-go/lib/client.(*Client).get(0xc420439670, 0x1eeee40, 0xc420242d90, 0x1efc4c0, 0xc4201162a0, 0x8, 0x8, 0xc4201162a0, 0x0)
May 08 23:03:21 node-01 kubelet[15267]:         /go/src/github.com/projectcalico/cni-plugin/vendor/github.com/projectcalico/libcalico-go/lib/client/client.go:290 +0xef
May 08 23:03:21 node-01 kubelet[15267]: github.com/projectcalico/cni-plugin/vendor/github.com/projectcalico/libcalico-go/lib/client.(*workloadEndpoints).Get(0xc4201162a0, 0x0, 0x0, 0xc42000e05b, 0x4, 0xc4203691a0, 0x21, 0x162b2af, 0x3, 0xc4204389a0, ...)
May 08 23:03:21 node-01 kubelet[15267]:         /go/src/github.com/projectcalico/cni-plugin/vendor/github.com/projectcalico/libcalico-go/lib/client/workloadendpoint.go:71 +0xc1
May 08 23:03:21 node-01 kubelet[15267]: github.com/projectcalico/cni-plugin/k8s.CmdDelK8s(0xc420439670, 0x0, 0x0, 0xc42000e05b, 0x4, 0xc4203691a0, 0x21, 0x162b2af, 0x3, 0xc4204389a0, ...)
May 08 23:03:21 node-01 kubelet[15267]:         /go/src/github.com/projectcalico/cni-plugin/k8s/k8s.go:306 +0xaa
May 08 23:03:21 node-01 kubelet[15267]: main.cmdDel(0xc4204120e0, 0xc420438498, 0x5)
May 08 23:03:21 node-01 kubelet[15267]:         /go/src/github.com/projectcalico/cni-plugin/calico.go:325 +0x9e8
May 08 23:03:21 node-01 kubelet[15267]: github.com/projectcalico/cni-plugin/vendor/github.com/containernetworking/cni/pkg/skel.(*dispatcher).checkVersionAndCall(0xc420178d40, 0xc4204120e0, 0x1ef1180, 0xc42001a600, 0x169c470, 0x0, 0xc420298b60)
May 08 23:03:21 node-01 kubelet[15267]:         /go/src/github.com/projectcalico/cni-plugin/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:162 +0x19f
May 08 23:03:21 node-01 kubelet[15267]: github.com/projectcalico/cni-plugin/vendor/github.com/containernetworking/cni/pkg/skel.(*dispatcher).pluginMain(0xc420178d40, 0x169c468, 0x169c470, 0x1ef1180, 0xc42001a600, 0xc420645f00)
May 08 23:03:21 node-01 kubelet[15267]:         /go/src/github.com/projectcalico/cni-plugin/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:175 +0x2af
May 08 23:03:21 node-01 kubelet[15267]: github.com/projectcalico/cni-plugin/vendor/github.com/containernetworking/cni/pkg/skel.PluginMainWithError(0x169c468, 0x169c470, 0x1ef1180, 0xc42001a600, 0xbc)
May 08 23:03:21 node-01 kubelet[15267]:         /go/src/github.com/projectcalico/cni-plugin/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:210 +0xed
May 08 23:03:21 node-01 kubelet[15267]: github.com/projectcalico/cni-plugin/vendor/github.com/containernetworking/cni/pkg/skel.PluginMain(0x169c468, 0x169c470, 0x1ef1180, 0xc42001a600)
May 08 23:03:21 node-01 kubelet[15267]:         /go/src/github.com/projectcalico/cni-plugin/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:222 +0x56
May 08 23:03:21 node-01 kubelet[15267]: main.main()
May 08 23:03:21 node-01 kubelet[15267]:         /go/src/github.com/projectcalico/cni-plugin/calico.go:375 +0x192
May 08 23:03:21 node-01 kubelet[15267]: E0508 23:03:21.671077   15267 cni.go:307] Error deleting network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input
May 08 23:03:21 node-01 kubelet[15267]: E0508 23:03:21.672239   15267 remote_runtime.go:109] StopPodSandbox "cf6b2529fe92e81741f83a85b3855f44cc6810eb060fcb10a8aafc55c563252f" from runtime service failed: rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod "my-nginx-3047691970-t46th_default" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input
May 08 23:03:21 node-01 kubelet[15267]: E0508 23:03:21.672313   15267 kuberuntime_manager.go:779] Failed to stop sandbox {"docker" "cf6b2529fe92e81741f83a85b3855f44cc6810eb060fcb10a8aafc55c563252f"}
May 08 23:03:21 node-01 kubelet[15267]: E0508 23:03:21.672346   15267 kubelet.go:1418] error killing pod: failed to "KillPodSandbox" for "61270e6c-3442-11e7-9f7f-080027ee3298" with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod \"my-nginx-3047691970-t46th_default\" network: netplugin failed but error parsing its diagnostic message \"\": unexpected end of JSON input"
May 08 23:03:21 node-01 kubelet[15267]: E0508 23:03:21.672368   15267 pod_workers.go:182] Error syncing pod 61270e6c-3442-11e7-9f7f-080027ee3298 ("my-nginx-3047691970-t46th_default(61270e6c-3442-11e7-9f7f-080027ee3298)"), skipping: error killing pod: failed to "KillPodSandbox" for "61270e6c-3442-11e7-9f7f-080027ee3298" with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod \"my-nginx-3047691970-t46th_default\" network: netplugin failed but error parsing its diagnostic message \"\": unexpected end of JSON input"
May 08 23:03:21 node-01 kubelet[15267]: I0508 23:03:21.682960   15267 reconciler.go:190] UnmountVolume operation started for volume "kubernetes.io/secret/61270e6c-3442-11e7-9f7f-080027ee3298-default-token-n2397" (spec.Name: "default-token-n2397") from pod "61270e6c-3442-11e7-9f7f-080027ee3298" (UID: "61270e6c-3442-11e7-9f7f-080027ee3298").
May 08 23:03:21 node-01 kubelet[15267]: I0508 23:03:21.707610   15267 operation_generator.go:638] UnmountVolume.TearDown succeeded for volume "kubernetes.io/secret/61270e6c-3442-11e7-9f7f-080027ee3298-default-token-n2397" (OuterVolumeSpecName: "default-token-n2397") pod "61270e6c-3442-11e7-9f7f-080027ee3298" (UID: "61270e6c-3442-11e7-9f7f-080027ee3298"). InnerVolumeSpecName "default-token-n2397". PluginName "kubernetes.io/secret", VolumeGidValue ""
May 08 23:03:21 node-01 kubelet[15267]: I0508 23:03:21.790781   15267 reconciler.go:352] Detached volume "kubernetes.io/secret/61270e6c-3442-11e7-9f7f-080027ee3298-default-token-n2397" (spec.Name: "default-token-n2397") devicePath: ""
May 08 23:03:22 node-01 kubelet[15267]: W0508 23:03:22.548905   15267 docker_sandbox.go:285] NetworkPlugin cni failed on the status hook for pod "my-nginx-3047691970-t46th_default": Unexpected command output nsenter: cannot open : No such file or directory
May 08 23:03:22 node-01 kubelet[15267]:  with error: exit status 1
```

### PR DESCRIPTION
**Pull request by gunjan5**
fixes #415

### CODE REVIEW

File: lib/backend/k8s/k8s.go [hunk 1]
```diff
@@ -499,13 +499,19 @@ func (c *KubeClient) listWorkloadEndpoints(l model.WorkloadEndpointListOptions)
...
-			return nil, err
+			switch err.(type) {
+			case errors.ErrorResourceDoesNotExist:
+				return []*model.KVPair{}, nil
+			default:
+				return nil, err
+			}
 		}
+
 		if kvp == nil {
```
Comment (caseydavenport) [inline lib/backend/k8s/k8s.go]: Is this branch still valid?  Seems like a duplicate of the error handling above - can we remove?

**Comment by caseydavenport** [comment]
One question for you - can you remove that stale branch (provided it's not necessary), give a quick re-test and then merge?

**Comment by gunjan5** [comment]
@caseydavenport ok tested this with CNI and KDD backend:
- create new pod (List returns nil during ADD)
- delete pod (Get returns ok during DEL)
- restart docker daemon so `ADD` gets called for an existing WEP, so CNI code takes the path where get WEP list returns something - non-nil

- all of that looks good

I squashed 2 issues in 2 commits. Going to merge now
