### PR TITLE
IPAM.ReleaseIPs de-dupes when unallocating

### LINKED ISSUE #989: IPAM Block does not protect against duplicates in Unallocated list
[`AllocationBlock`](https://github.com/projectcalico/libcalico-go/blob/release-v3.4/lib/backend/model/block.go#L91) is a simple list and the code always assumes the values are unique.

## Expected Behavior

1. An assigned IP should not be assigned twice!
1. Whenever releasing IPs, the supplied list of IPs should be de-duped and handled defensively.

## Current Behavior

`IPAM.ReleaseIPs()` happily accepts a list of IPs that contains duplicates. This will leave duplicates in `Unallocated` which then creates more havoc, in particular **assigning already assigned IPs**.

Reproduced the behaviour in an e2e test: https://github.com/projectcalico/libcalico-go/pull/990

## Possible Solution

Validate ReleaseIPs input and also add checks to [`ipam_block.go`'s `release()` function](https://github.com/projectcalico/libcalico-go/blob/release-v3.4/lib/ipam/ipam_block.go#L203-L206) to stop duplicates being added. Ideally use `lib/set` to avoid bugs like this occurring again.

## Steps to Reproduce (for bugs)

Call `ReleaseIPs([]cnet.IP{ip, ip}` with a duplicate entry in the list, then keeping assigning IPs and you will eventually get `ip` assigned twice.

Have now observed multiple instances of doubly-assigned IPs in running production cluster.

Doing a quick audit reveals an IP block with duplicates in the unallocated list, but have observed other IP pools with the same issue:

```
for subnet in $(etcdctl ls --sort /calico/ipam/v2/assignment/ipv4/block)
do
    etcdctl get $subnet | jq 'if (.unallocated | length) != (.unallocated | unique | length) then "duplicate found \(.cidr)" else empty end'
done
```

## Context

A running container has it's IP assigned to another container. Whichever exits first will release that IP leaving the other with an IP that's been released. Rinse-and-repeat.

## Your Environment

Calico 2.6.12, running Docker with libnetwork on Mesos.

* libcalico-go version: 1.7.3
* Operating System and version: Ubuntu 18.04 bionic
* Link to your project (optional):

### PR DESCRIPTION
**Pull request by jsok**
## Description

IPAM.ReleaseIPs() happily accepts a list of IPs that contains
duplicates. This will leave duplicates in Unallocated which then creates
more havoc, in particular assigning already assigned IPs.

De-dupe the list of addresses before calculating ordinals to be
unalloacted.

Fixes #989

Port of #990 to `master` branch.

## Todos
- [x] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

TBA

### CODE REVIEW

File: lib/ipam/ipam_test.go [hunk 1]
```diff
@@ -1133,7 +1186,7 @@ var _ = testutils.E2eDatastoreDescribe("IPAM tests", testutils.DatastoreEtcdV3,
 		// - Assign should not return no error.
 		// - ReleaseIPs should return a slice with one (unallocatedIPs) and no error.
 		Entry("Assign 1 IPv4 address with AssignIP then try to release 2 IPs (assign one and release it)", net.IP{}, true, []string{"192.168.1.0/24", "fd80:24e2:f998:72d6::/120"}, net.ParseIP("192.168.1.0"), 0, []cnet.IP{}, nil),
-		Entry("Assign 1 IPv4 address with AssignIP then try to release 2 IPs (release a second one)", net.ParseIP("192.168.1.1"), false, []string{"192.168.1.0/24", "fd80:24e2:f998:72d6::/120"}, net.IP{}, 0, []cnet.IP{{net.ParseIP("192.168.1.1")}}, nil),
+		Entry("Assign 1 IPv4 address with AssignIP then try to release 2 IPs (release a second one)", net.ParseIP("192.168.1.1"), false, []string{"192.168.1.0/24", "fd80:24e2:f998:72d6::/120"}, net.IP{}, 0, []cnet.IP{cnet.MustParseIP("192.168.1.1")}, nil),
```
Comment (jsok) [inline lib/ipam/ipam_test.go]: Getting failure:

```

  Expected

      <[]net.IP | len:1, cap:1>: [

          {IP: [192, 168, 1, 1]},

      ]

  to equal

      <[]net.IP | len:1, cap:1>: [

          {

              IP: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 255, 255, 192, 168, 1, 1],

          },

      ]



  /go/src/github.com/projectcalico/libcalico-go/lib/ipam/ipam_test.go:1157
```

This is presumably because gomega `Equal` matcher is using `reflect.DeepEqual` rather than `net.IP.Equal`. Now that the de-duping going from IP -> String -> IP the embedded IPv4/v6 struct is getting mixed up in the tests :(
