### PR TITLE
Felix config intervals

### LINKED ISSUE #712: FelixConfig loses precision vs Felix's config parser
Felix supports fractional seconds/millis for `time.Duration` fields but those have been mapped through to `*int`s on the FelixConfig type.

## Expected Behavior

Should be able to set a fractional number of seconds for, say `IptablesPostWriteCheckIntervalSecs`, but it's typed as an int.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* libcalico-go version:
* Operating System and version:
* Link to your project (optional):

### PR DESCRIPTION
**Pull request by heschlie**
## Description

Fixes #712 
Changing the type for all of the `FexixConfigurationSpec.*Secs` to be of type `*time.Duration` instead of `*int` to ensure we don't loose precision and to match what Felix uses (as we can do fractional seconds in Felix) and setting `config:"seconds"` to match what Felix expects.

## Todos
- [x] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

File: lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go [hunk 1]
```diff
@@ -206,7 +207,7 @@ var _ = Describe("Test the generic configuration update processor and the concre
 			},
 		}
 		expected := map[string]interface{}{
-			"RouteRefreshInterval":      "12345",
```
Comment (fasaxc) [inline lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go]: Is this the output that felix will see?  Sadly, felix has its own parse for these rather than parsing them as durations. If the felix value is in seconds, then it expects a float `10.5` with no `s` suffix, if the felix value is in millis, then it expects `10500.0`

Comment (heschlie) [reply lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go]: I was wondering about this, I'll see if I can get it to output floats from the converter.

File: lib/apis/v3/felixconfig.go [hunk 2]
```diff
@@ -46,19 +47,19 @@ type FelixConfigurationSpec struct {
 	// RouterefreshInterval is the period, in seconds, at which Felix re-checks the routes
 	// in the dataplane to ensure that no other process has accidentally broken Calico’s rules.
 	// Set to 0 to disable route refresh. [Default: 90]
-	RouteRefreshIntervalSecs *int `json:"routeRefreshIntervalSecs,omitempty" confignamev1:"RouteRefreshInterval"`
+	RouteRefreshIntervalSecs *time.Duration `json:"routeRefreshIntervalSecs,omitempty" config:"seconds" confignamev1:"RouteRefreshInterval"`
```
Comment (robbrockbank) [inline lib/apis/v3/felixconfig.go]: None of these fields should have the units suffix (e.g. Secs / Millis) - the time.Duration is already takes care of units for you.

Comment (robbrockbank) [reply lib/apis/v3/felixconfig.go]: Also we should use the kubernetes definition of `Duration` in `k8s.io/apimachinery/pkg/apis/meta/v1`

File: lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go (hunk 1 above)
Comment (robbrockbank) [reply lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go]: I also think it depends on the fields - some are millis and some are s.

@fasaxc :  Are all the duration/interval fields floats, or just the secs ones?  What about the millisecond interval fields?

File: lib/apis/v3/felixconfig.go (hunk 2 above)
Comment (fasaxc) [reply lib/apis/v3/felixconfig.go]: If you change the names, you'll need to fix up the Felix UT here, which asserts that the name is either the same, or in a map of exceptions: https://github.com/projectcalico/felix/blob/master/config/config_params_test.go#L50

Comment (fasaxc) [reply lib/apis/v3/felixconfig.go]: There may also be downstream STs that use the new config struct

File: lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go (hunk 1 above)
Comment (fasaxc) [reply lib/backend/syncersv1/updateprocessors/configurationprocessor_test.go]: @robbrockbank They're all parsed as floats now.

**Comment by heschlie** [comment]
@fasaxc I was pointed to the right spot to coerce these into floats for Felix, we should be set there.

File: lib/apis/v3/felixconfig.go [hunk 3]
```diff
@@ -46,40 +46,40 @@ type FelixConfigurationSpec struct {
...
 	// [Default: 0 disabled]
-	IptablesLockTimeoutSecs *int `json:"iptablesLockTimeoutSecs,omitempty"`
-	// IptablesLockProbeIntervalMillis is the time, in milliseconds, that Felix will wait between
+	IptablesLockTimeout *metav1.Duration `json:"iptablesLockTimeoutSecs,omitempty" configv1timescale:"seconds" confignamev1:"IptablesLockTimeoutSecs"`
+	// IptablesLockProbeInterval is the time, in milliseconds, that Felix will wait between
 	// attempts to acquire the iptables lock if it is not available. Lower values make Felix more
 	// responsive when the lock is contended, but use more CPU. [Default: 50]
-	IptablesLockProbeIntervalMillis *int `json:"iptablesLockProbeIntervalMillis,omitempty"`
-	// IpsetsRefreshIntervalSecs is the period, in seconds, at which Felix re-checks all iptables
+	IptablesLockProbeInterval *metav1.Duration `json:"iptablesLockProbeIntervalMillis,omitempty" configv1timescale:"milliseconds"`
```
Comment (fasaxc) [inline lib/apis/v3/felixconfig.go]: Needs a `confignamev1`

File: lib/backend/syncersv1/updateprocessors/configurationprocessor.go [hunk 4]
```diff
@@ -230,6 +231,13 @@ func (c *configUpdateProcessor) processAddOrModified(kvp *model.KVPair) ([]*mode
 				switch vt := value.(type) {
 				case string:
 					value = vt
+				case v1.Duration:
+					switch fieldInfo.Tag.Get("configv1timescale") {
+					case "seconds":
+						value = fmt.Sprintf("%.1f", vt.Seconds())
+					case "milliseconds":
+						value = fmt.Sprintf("%.1f", float64(vt.Duration/time.Millisecond))
+					}
```
Comment (fasaxc) [inline lib/backend/syncersv1/updateprocessors/configurationprocessor.go]: Bit worried that it'd be easy to leave this tag out when adding a new field.  Should we default to seconds?

File: lib/backend/syncersv1/updateprocessors/configurationprocessor.go [hunk 5]
```diff
@@ -230,6 +231,13 @@ func (c *configUpdateProcessor) processAddOrModified(kvp *model.KVPair) ([]*mode
 				switch vt := value.(type) {
 				case string:
 					value = vt
+				case v1.Duration:
+					switch fieldInfo.Tag.Get("configv1timescale") {
+					case "seconds":
+						value = fmt.Sprintf("%.1f", vt.Seconds())
```
Comment (fasaxc) [inline lib/backend/syncersv1/updateprocessors/configurationprocessor.go]: I think `.1` might be a bit limiting, how about `.3` so that seconds can express millisecond precision and millis can express microseconds.  That should be more than enough.

File: lib/backend/syncersv1/updateprocessors/configurationprocessor.go (hunk 4 above)
Comment (heschlie) [reply lib/backend/syncersv1/updateprocessors/configurationprocessor.go]: I think there is only one field that uses ms, so it would make some sense.

Comment (heschlie) [reply lib/backend/syncersv1/updateprocessors/configurationprocessor.go]: Yea good catch.

File: lib/apis/v3/felixconfig.go [hunk 6]
```diff
@@ -46,40 +46,40 @@ type FelixConfigurationSpec struct {
...
+	// IpsetsRefreshInterval is the period, in seconds, at which Felix re-checks all iptables
 	// state to ensure that no other process has accidentally broken Calico’s rules. Set to 0 to
 	// disable iptables refresh. [Default: 90]
-	IpsetsRefreshIntervalSecs *int `json:"ipsetsRefreshIntervalSecs,omitempty" confignamev1:"IpsetsRefreshInterval"`
+	IpsetsRefreshInterval *metav1.Duration `json:"ipsetsRefreshIntervalSecs,omitempty" configv1timescale:"seconds" confignamev1:"IpsetsRefreshInterval"`
```
Comment (robbrockbank) [inline lib/apis/v3/felixconfig.go]: Now that the name has reverted back to the original, we no longer need the confignamev1 tag.

File: lib/apis/v3/felixconfig.go [hunk 7]
```diff
@@ -135,14 +135,14 @@ type FelixConfigurationSpec struct {
...
 	IPIPMTU *int `json:"ipipMTU,omitempty" confignamev1:"IpInIpMtu"`
 
-	// ReportingIntervalSecs is the interval at which Felix reports its status into the datastore or 0 to disable.
+	// ReportingInterval is the interval at which Felix reports its status into the datastore or 0 to disable.
 	// Must be non-zero in OpenStack deployments. [Default: 30]
-	ReportingIntervalSecs *int `json:"reportingIntervalSecs,omitempty"`
-	// ReportingTTLSecs is the time-to-live setting for process-wide status reports. [Default: 90]
-	ReportingTTLSecs *int `json:"reportingTTLSecs,omitempty"`
+	ReportingInterval *metav1.Duration `json:"reportingIntervalSecs,omitempty" configv1timescale:"seconds" confignamev1:"ReportingIntervalSecs"`
+	// ReportingTTL is the time-to-live setting for process-wide status reports. [Default: 90]
```
Comment (robbrockbank) [inline lib/apis/v3/felixconfig.go]: default is 90s

File: lib/apis/v3/felixconfig.go [hunk 8]
```diff
@@ -46,40 +46,40 @@ type FelixConfigurationSpec struct {
...
+	IptablesLockTimeout *metav1.Duration `json:"iptablesLockTimeoutSecs,omitempty" configv1timescale:"seconds" confignamev1:"IptablesLockTimeoutSecs"`
+	// IptablesLockProbeInterval is the time, in milliseconds, that Felix will wait between
 	// attempts to acquire the iptables lock if it is not available. Lower values make Felix more
 	// responsive when the lock is contended, but use more CPU. [Default: 50]
-	IptablesLockProbeIntervalMillis *int `json:"iptablesLockProbeIntervalMillis,omitempty"`
-	// IpsetsRefreshIntervalSecs is the period, in seconds, at which Felix re-checks all iptables
+	IptablesLockProbeInterval *metav1.Duration `json:"iptablesLockProbeIntervalMillis,omitempty" configv1timescale:"milliseconds"`
+	// IpsetsRefreshInterval is the period, in seconds, at which Felix re-checks all iptables
 	// state to ensure that no other process has accidentally broken Calico’s rules. Set to 0 to
 	// disable iptables refresh. [Default: 90]
```
Comment (robbrockbank) [inline lib/apis/v3/felixconfig.go]: Default: 90s

File: lib/apis/v3/felixconfig.go (hunk 3 above)
Comment (robbrockbank) [reply lib/apis/v3/felixconfig.go]: and comment should be Default: 50ms

File: lib/apis/v3/felixconfig.go [hunk 9]
```diff
@@ -46,40 +46,40 @@ type FelixConfigurationSpec struct {
 	// RouterefreshInterval is the period, in seconds, at which Felix re-checks the routes
 	// in the dataplane to ensure that no other process has accidentally broken Calico’s rules.
 	// Set to 0 to disable route refresh. [Default: 90]
-	RouteRefreshIntervalSecs *int `json:"routeRefreshIntervalSecs,omitempty" confignamev1:"RouteRefreshInterval"`
+	RouteRefreshInterval *metav1.Duration `json:"routeRefreshIntervalSecs,omitempty" configv1timescale:"seconds" confignamev1:"RouteRefreshInterval"`
```
Comment (robbrockbank) [inline lib/apis/v3/felixconfig.go]: Default: 90s

File: lib/apis/v3/felixconfig.go [hunk 10]
```diff
@@ -46,40 +46,40 @@ type FelixConfigurationSpec struct {
...
 	// IptablesRefreshInterval is the period, in seconds, at which Felix re-checks the IP sets
 	// in the dataplane to ensure that no other process has accidentally broken Calico’s rules.
 	// Set to 0 to disable IP sets refresh. Note: the default for this value is lower than the
 	// other refresh intervals as a workaround for a Linux kernel bug that was fixed in kernel
 	// version 4.11. If you are using v4.11 or greater you may want to set this to, a higher value
 	// to reduce Felix CPU usage. [Default: 10]
-	IptablesRefreshIntervalSecs *int `json:"iptablesRefreshIntervalSecs,omitempty" confignamev1:"IptablesRefreshInterval"`
-	// IptablesPostWriteCheckIntervalSecs is the period, in seconds, after Felix has done a write
+	IptablesRefreshInterval *metav1.Duration `json:"iptablesRefreshIntervalSecs,omitempty" configv1timescale:"seconds" confignamev1:"IptablesRefreshInterval"`
```
Comment (robbrockbank) [inline lib/apis/v3/felixconfig.go]: Default 10s

File: lib/apis/v3/felixconfig.go [hunk 11]
```diff
@@ -46,40 +46,40 @@ type FelixConfigurationSpec struct {
...
+	// IptablesPostWriteCheckInterval is the period, in seconds, after Felix has done a write
 	// to the dataplane that it schedules an extra read back in order to check the write was not
 	// clobbered by another process. This should only occur if another application on the system
 	// doesn’t respect the iptables lock. [Default: 1]
-	IptablesPostWriteCheckIntervalSecs *int `json:"iptablesPostWriteCheckIntervalSecs,omitempty"`
+	IptablesPostWriteCheckInterval *metav1.Duration `json:"iptablesPostWriteCheckIntervalSecs,omitempty" configv1timescale:"seconds" confignamev1:"IptablesPostWriteCheckIntervalSecs"`
```
Comment (robbrockbank) [inline lib/apis/v3/felixconfig.go]: Default: 1s

File: lib/apis/v3/felixconfig.go [hunk 12]
```diff
@@ -135,14 +135,14 @@ type FelixConfigurationSpec struct {
 	// IPIPMTU is the MTU to set on the tunnel device. See Configuring MTU [Default: 1440]
 	IPIPMTU *int `json:"ipipMTU,omitempty" confignamev1:"IpInIpMtu"`
 
-	// ReportingIntervalSecs is the interval at which Felix reports its status into the datastore or 0 to disable.
+	// ReportingInterval is the interval at which Felix reports its status into the datastore or 0 to disable.
```
Comment (robbrockbank) [inline lib/apis/v3/felixconfig.go]: Default 30s

File: lib/apis/v3/felixconfig.go (hunk 7 above)
Comment (robbrockbank) [reply lib/apis/v3/felixconfig.go]: and other defaults can be updated below too.

**Comment by heschlie** [comment]
@fasaxc The build I've posted passes tests locally but Semaphore seems to be having SSL issues. This is ready for another look.

**Comment by fasaxc** [comment]
Reran the tests but they hit a failure this time.  Given you're working in a different area of the codebase, I've raised an issue on the assumption that it's a flake: https://github.com/projectcalico/libcalico-go/issues/732

File: lib/apis/v3/felixconfig.go [hunk 13]
```diff
@@ -45,41 +45,41 @@ type FelixConfigurationSpec struct {
 
 	// RouterefreshInterval is the period, in seconds, at which Felix re-checks the routes
 	// in the dataplane to ensure that no other process has accidentally broken Calico’s rules.
-	// Set to 0 to disable route refresh. [Default: 90]
-	RouteRefreshIntervalSecs *int `json:"routeRefreshIntervalSecs,omitempty" confignamev1:"RouteRefreshInterval"`
+	// Set to 0 to disable route refresh. [Default: 90s]
+	RouteRefreshInterval *metav1.Duration `json:"routeRefreshIntervalSecs,omitempty" configv1timescale:"seconds" confignamev1:"RouteRefreshInterval"`
```
Comment (robbrockbank) [inline lib/apis/v3/felixconfig.go]: confignamev1 is not required here anymore.
